#!/bin/bash
#
# basic PI setup

# curl https://raw.githubusercontent.com/sroller/himbeere/main/setup_himbeere | bash

set -x

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install tmux vim gpg git nfs-common ruby locate

# set timezone

# install RVM
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash -s stable --ruby

# set aliases in .bashrcf

# download tmux.conf

# download colorscheme molokai et al

# download vimrc.local

# install motion

# add /nfs

